version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "dracorisz"
    assignees:
      - "dracorisz"
    labels:
      - "dependencies"
      - "dependabot"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "dracorisz"
    assignees:
      - "dracorisz"
    labels:
      - "dependencies"
      - "dependabot"
