import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('button keeps canonical typography, geometry and direct icon size through shared tokens', async () => {
  const button = await read('src/components/ui/Button.tsx')
  const tokens = await read('src/components/ui/buttonStyles.ts')
  assert.match(button, /buttonBaseClass/)
  assert.match(button, /buttonVariantClasses/)
  assert.match(button, /buttonSizeClasses/)
  assert.match(tokens, /text-sm/)
  assert.match(tokens, /sm:\s*["']h-9 min-h-9 max-h-9 px-2["']/)
  assert.match(tokens, /md:\s*["']h-9 min-h-9 max-h-9 px-4["']/)
  assert.match(tokens, /lg:\s*["']h-9 min-h-9 max-h-9 px-8["']/)
  assert.match(tokens, /\[&>svg\]:h-4 \[&>svg\]:w-4/)
  assert.match(tokens, /has-\[img\]:h-auto has-\[img\]:max-h-none/)
  assert.match(tokens, /has-\[video\]:h-auto has-\[video\]:max-h-none/)
  assert.match(tokens, /focus-visible:ring-1/)
})

test('icon button uses the same variants, focus treatment and icon sizing', async () => {
  const source = await read('src/components/ui/IconButton.tsx')
  const tokens = await read('src/components/ui/buttonStyles.ts')
  assert.match(source, /buttonBaseClass/)
  assert.match(source, /buttonVariantClasses/)
  assert.match(source, /iconButtonSizeClasses/)
  assert.match(source, /aria-label=\{label\}/)
  assert.match(tokens, /sm:\s*["']h-9 min-h-9 max-h-9 w-9["']/)
})

test('form controls share one canonical 36px token source and native fallbacks', async () => {
  const tokens = await read('src/components/ui/controlStyles.ts')
  const inputs = await read('src/components/ui/Inputs.tsx')
  const select = await read('src/components/ui/Select.tsx')
  const css = await read('src/index.css')
  const tailwind = await read('tailwind.config.js')
  assert.match(tokens, /h-9 min-h-9 max-h-9/)
  assert.match(tokens, /px-4 text-sm/)
  assert.match(tokens, /rounded-xl/)
  assert.match(tokens, /focus:ring-1/)
  assert.match(inputs, /controlClass, controlLabelClass/)
  assert.match(select, /controlClass, controlLabelClass/)
  assert.match(css, /--control-height:\s*2\.25rem/)
  assert.match(css, /--control-line-height:/)
  assert.match(css, /height:\s*var\(--control-height\)/)
  assert.match(css, /input:not\(\[type=["']checkbox["']\]\)/)
  assert.match(css, /select, textarea/)
  assert.match(tailwind, /9:\s*["']var\(--control-height\)["']/)
})

test('typography primitives expose only the intentional hierarchy', async () => {
  const heading = await read('src/components/ui/Heading.tsx')
  const typography = await read('src/components/ui/Typography.tsx')
  assert.match(heading, /hero:\s*["']text-5xl/)
  assert.match(heading, /title:\s*["']text-lg/)
  assert.match(heading, /compact:\s*["']text-sm/)
  assert.match(typography, /body:\s*["']text-sm/)
  assert.match(typography, /title:\s*["']text-lg/)
  assert.match(typography, /hero:\s*["']text-5xl/)
  assert.doesNotMatch(`${heading}\n${typography}`, /text-(?:base|xl|2xl|3xl|4xl|6xl|7xl|8xl|9xl)/)
})

test('surface primitive owns canonical visual surface variants', async () => {
  const surface = await read('src/components/ui/Surface.tsx')
  const card = await read('src/components/ui/Card.tsx')
  assert.match(surface, /surface-card/)
  assert.match(surface, /surface-panel/)
  assert.match(surface, /surface-muted/)
  assert.match(surface, /surface-popover shadow-xl/)
  assert.match(surface, /p-2/)
  assert.match(surface, /p-4/)
  assert.match(surface, /p-8/)
  assert.match(card, /<Surface/)
})

test('semantic palette, radius, borders, shadow and height have central token sources', async () => {
  const tailwind = await read('tailwind.config.js')
  const css = await read('src/index.css')
  assert.match(tailwind, /success:/)
  assert.match(tailwind, /warning:/)
  assert.match(tailwind, /info:/)
  assert.match(tailwind, /overlay:/)
  assert.match(tailwind, /inverse:/)
  assert.match(tailwind, /xl:\s*["']var\(--radius\)["']/)
  assert.match(tailwind, /xl:\s*["']var\(--shadow-xl\)["']/)
  assert.match(css, /--radius:\s*0\.35rem/)
  assert.match(css, /--control-height:\s*2\.25rem/)
  assert.match(css, /--pill-height:/)
  assert.match(css, /--border-opacity:/)
  assert.match(css, /--surface-border-opacity:/)
  assert.match(css, /--shadow-xl:/)
  assert.match(css, /--success:/)
  assert.match(css, /--warning:/)
  assert.match(css, /--info:/)
})

test('badges use standard UI text and centrally configured pill geometry', async () => {
  const badge = await read('src/components/ui/Badge.tsx')
  const buildBadge = await read('src/components/ui/BuildBadge.tsx')
  const css = await read('src/index.css')
  assert.match(badge, /app-pill.*rounded-xl.*border.*px-2 text-sm/)
  assert.match(buildBadge, /app-pill.*rounded-xl.*border.*px-2.*text-sm/)
  assert.match(css, /\.app-pill[\s\S]*height:\s*var\(--pill-height\)/)
})

test('Media Vault makes managed folders read-only for manual uploads', async () => {
  const source = await read('src/components/dashboard/PF_UserMediaVault.tsx')
  assert.match(source, /MANAGED_FOLDERS = new Set\(\[["']desktop-buddies["'], ["']screenshots["'], ["']dragon-arena["'], ["']getter-pro["']\]\)/)
  assert.match(source, /\{ value: ["']general["'], label: ["']General["'] \}/)
  assert.match(source, /Uploads are disabled in this managed folder/)
  assert.match(source, /Managed folder · uploads disabled/)
  assert.match(source, /uploadsRestricted \? \(/)
  assert.match(source, /padding=\{list \? 4 : 0\}/)
  assert.match(source, /style=\{\{ padding: 0 \}\}/)
  assert.match(source, /flex shrink-0 flex-col items-start gap-2/)
})

test('file picker actions use a button and keep the native input outside labels', async () => {
  const source = await read('src/components/ui/FileButton.tsx')
  assert.match(source, /<input ref=\{setRef\} type="file"/)
  assert.match(source, /<Button/)
  assert.doesNotMatch(source, /<label/)

  const favicon = await read('src/components/public/FaviconStudio.tsx')
  assert.match(favicon, /grid grid-cols-2 gap-2 pt-2/)
  assert.match(favicon, /grid grid-cols-3 gap-4/)
  assert.match(favicon, /width=\{16\} height=\{16\}/)
})

test('folded sidebar keeps centered icons and a vertically scrollable app rail', async () => {
  const source = await read('src/components/layout/Sidebar.tsx')
  assert.match(source, /group\/sidebar/)
  assert.match(source, /w-16 border-r border-border hover:w-64/)
  assert.match(source, /w-full justify-center px-2 group-hover\/sidebar:justify-start group-hover\/sidebar:px-4/)
  assert.match(source, /min-h-0 flex-1 overflow-y-auto overflow-x-hidden/)
  assert.match(source, /group-hover\/sidebar:block/)
  assert.match(source, /group-hover\/sidebar:flex-row/)
})

test('UI style checker enforces the project token contract and bans page-level native controls', async () => {
  const source = await read('scripts/check-ui-style.mjs')
  assert.match(source, /allowedFontSizes = new Set\(\['text-5xl', 'text-lg', 'text-sm'\]\)/)
  assert.match(source, /allowedSpacing = new Set\(\['2', '4', '8'\]\)/)
  assert.match(source, /text-xs requires an explicit design-xs-ok exception/)
  assert.match(source, /hard-coded palette utility/)
  assert.match(source, /noncanonical font weight/)
  assert.match(source, /forbidden radius/)
  assert.match(source, /forbidden shadow/)
  assert.match(source, /forbidden ring width/)
  assert.match(source, /rawControlBudget = 0/)
  assert.match(source, /process\.exit\(1\)/)
})
