create table if not exists public.dragon_arena_daily_usage (
  user_id uuid primary key references auth.users(id) on delete cascade,
  usage_date date not null default (timezone('utc', now()))::date,
  request_count integer not null default 0 check (request_count >= 0),
  updated_at timestamptz not null default now()
);

alter table public.dragon_arena_daily_usage enable row level security;

create policy "Users can read own Dragon Arena usage"
on public.dragon_arena_daily_usage
for select
to authenticated
using ((select auth.uid()) = user_id);

create table if not exists public.dragon_arena_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text,
  summary text,
  turn_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.dragon_arena_sessions enable row level security;
create policy "Users manage own Dragon Arena sessions"
on public.dragon_arena_sessions
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create index if not exists dragon_arena_sessions_user_updated_idx
  on public.dragon_arena_sessions(user_id, updated_at desc);

create table if not exists public.dragon_arena_turns (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.dragon_arena_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  turn_number integer not null,
  player_action text not null,
  narrative text not null,
  choices jsonb not null default '[]'::jsonb,
  model text not null,
  created_at timestamptz not null default now()
);

alter table public.dragon_arena_turns enable row level security;
create policy "Users manage own Dragon Arena turns"
on public.dragon_arena_turns
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create index if not exists dragon_arena_turns_session_idx
  on public.dragon_arena_turns(session_id, turn_number);

create table if not exists public.dragon_arena_assets (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.dragon_arena_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  asset_type text not null,
  storage_path text,
  external_url text,
  prompt text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.dragon_arena_assets enable row level security;
create policy "Users manage own Dragon Arena assets"
on public.dragon_arena_assets
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create index if not exists dragon_arena_assets_session_idx
  on public.dragon_arena_assets(session_id, created_at desc);

create or replace function public.consume_dragon_arena_daily_request()
returns boolean
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  uid uuid := auth.uid();
  today_utc date := (timezone('utc', now()))::date;
  current_count integer;
begin
  if uid is null then
    raise exception 'Authentication required';
  end if;

  insert into public.dragon_arena_daily_usage(user_id, usage_date, request_count, updated_at)
  values (uid, today_utc, 0, now())
  on conflict (user_id) do update
    set usage_date = case when dragon_arena_daily_usage.usage_date = today_utc then dragon_arena_daily_usage.usage_date else today_utc end,
        request_count = case when dragon_arena_daily_usage.usage_date = today_utc then dragon_arena_daily_usage.request_count else 0 end,
        updated_at = now();

  select request_count into current_count
  from public.dragon_arena_daily_usage
  where user_id = uid
  for update;

  if current_count >= 1 then
    return false;
  end if;

  update public.dragon_arena_daily_usage
  set request_count = request_count + 1, updated_at = now()
  where user_id = uid;

  return true;
end;
$$;

create or replace function public.refund_dragon_arena_daily_request()
returns void
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  uid uuid := auth.uid();
  today_utc date := (timezone('utc', now()))::date;
begin
  if uid is null then
    raise exception 'Authentication required';
  end if;

  update public.dragon_arena_daily_usage
  set request_count = greatest(request_count - 1, 0), updated_at = now()
  where user_id = uid and usage_date = today_utc;
end;
$$;
